### ISSUE TITLE
Add today if no date available

### ISSUE THREAD

**Issue by alfureu** [h43z/rssify#1]
Hi, love this script. I am struggling adding a piece of code to this if there is no date available on the website that can be parsed. Would it be possible to add the current date instead? I do not have sufficient coding experience for doing this, unfortunately, I wasted few days by trying to add it. :-(

**Comment by h43z** [comment]
I added it. I hope it works for you.

**Comment by alfureu** [comment]
Thanks, this works flawlessly, and of course much more elegant than any of my potential solutions. :-) Great thanks for this!

Is there any way how to define in `config.ini` a search interval for the parser? 

```html
<div.entry>   
   <h2>
     <strong> Title </strong>
       <p> Text </p>
     <strong> Title 2 </strong>
       <p> Text </p>
   <h2>
     <strong> Title 3 </strong>
       <p> Text </p>
</div>
```

What I would like to achieve to list the elements in `<strong></strong>` before the 2nd `<h2>`. Is this possible to set it in the `config.ini`, as I get few false positives due to the design of the page.

**Comment by h43z** [comment]
I think what you are looking for is the CSS selector [first-child](https://www.w3schools.com/cssref/sel_firstchild.asp)

In your case it should then be "div.entry > h2:first-child > strong"

**Comment by alfureu** [comment]
thanks @h43z, your comment helped a lot!
