### ISSUE TITLE
Add custom cookie for websites behind login

### ISSUE THREAD

**Issue by spinnaker1** [h43z/rssify#3]
Can you please add a custom cookie option into the code, so rssify is able to reach content behind a login-required website.

I would login to the website with Chrome and export the cookie data with txt cookie saver extension (or similar) and paste it into rssify script.

With "[Requests html](https://pypi.org/project/requests-html/) " this is possible.

**Comment by h43z** [comment]
im not even using this anymore myself. so no.

**Comment by spinnaker1** [comment]
If you found something better, feel free to share please. I'm searching a tool like this.

**Comment by alfureu** [comment]
I think [fivefiltersrss](https://hub.docker.com/r/heussd/fivefilters-full-text-rss) would be suitable for your needs
